### ISSUE TITLE
Changes this repo to a "Template Repo"

### ISSUE THREAD

**Issue by trickypr** [ajvincent/motherhen#17]
Given the goal of this repo, it would probably be a good idea to make it [a template repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository). This allows users to click a single button and have a copy of the repo on their own GitHub account, for example [this repo](https://github.com/TheCherno/WalnutAppTemplate).

**Comment by ajvincent** [comment]
Done, and thanks for the suggestion.
